"""
SQLAlchemy model for municipal complaints.

Fulfills all schema, field, constraint, enum, and index requirements
defined in the CivicPulse assignment specification.
"""

import enum
import uuid
from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Enum,
    Index,
    Integer,
    String,
    Uuid,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class CategoryEnum(enum.StrEnum):
    WATER = "water"
    ELECTRICITY = "electricity"
    SANITATION = "sanitation"
    ROADS = "roads"
    STREETLIGHTS = "streetlights"
    OTHER = "other"


class PriorityEnum(enum.StrEnum):
    HIGH = "high"
    NORMAL = "normal"
    LOW = "low"


class StatusEnum(enum.StrEnum):
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    RESOLVED = "resolved"
    REJECTED = "rejected"


class Complaint(Base):
    __tablename__ = "complaints"

    # Server-generated UUID primary key
    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    # Free-text description of the issue, 10-2000 characters
    text: Mapped[str] = mapped_column(
        String(2000),
        nullable=False,
    )

    # Location of the issue, 3-200 characters
    location: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
    )

    # Optional citizen reporter contact details
    reporter_contact: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
    )

    # Categorization enum
    category: Mapped[CategoryEnum] = mapped_column(
        Enum(CategoryEnum, name="complaint_category", native_enum=False),
        nullable=False,
    )

    # Priority level enum
    priority: Mapped[PriorityEnum] = mapped_column(
        Enum(PriorityEnum, name="complaint_priority", native_enum=False),
        nullable=False,
    )

    # Workflow status enum (defaults to open)
    status: Mapped[StatusEnum] = mapped_column(
        Enum(StatusEnum, name="complaint_status", native_enum=False),
        nullable=False,
        default=StatusEnum.OPEN,
    )

    # One-line summary generated by AI or rules (<= 140 chars)
    ai_summary: Mapped[str | None] = mapped_column(
        String(140),
        nullable=True,
    )

    # Identifier of the triage provider that categorized this complaint
    triaged_by: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
    )

    # Latency of the triage operation in milliseconds
    triage_latency_ms: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    # Timestamps in UTC
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    __table_args__ = (
        # DB-level length enforcement
        CheckConstraint(
            "length(text) >= 10 AND length(text) <= 2000",
            name="ck_complaints_text_length",
        ),
        CheckConstraint(
            "length(location) >= 3 AND length(location) <= 200",
            name="ck_complaints_location_length",
        ),
        # Required index for triage queue filtering by status and priority
        Index("ix_complaints_status_priority", "status", "priority"),
        # Required index for timestamp ordering and pagination queries
        Index("ix_complaints_created_at", "created_at"),
    )

    def __repr__(self) -> str:
        return (
            f"<Complaint id={self.id} category={self.category} "
            f"priority={self.priority} status={self.status}>"
        )
